import type { TraceEvent } from "./audit";

export const sampleTraces: TraceEvent[] = [
  {
    id: "tr_kyc_001",
    agentName: "KYC Review Copilot",
    workflow: "enhanced-diligence-summary",
    occurredAt: "2026-05-01T13:42:10.000Z",
    environment: "production-shadow",
    metadataOnly: true,
    rawPromptStored: false,
    customerDataStored: false,
    redactionClass: "metadata_only",
    retentionDays: 180,
    modelProvider: "OpenRouter",
    modelName: "anthropic/claude-3.5-haiku",
    actionCategory: "case-summary",
    policies: [
      { id: "pol_no_payload", name: "No customer payload retention", status: "pass", evidence: "Stored schema fields exclude prompt, account, transaction, and customer identifiers." },
      { id: "pol_redaction", name: "Redaction proof captured", status: "pass", evidence: "Redaction classifier returned metadata_only before persistence." },
      { id: "pol_retention", name: "Retention window under 365 days", status: "pass", evidence: "Trace retention set to 180 days." },
    ],
    approvals: [{ reviewerRole: "Compliance lead", status: "approved", decidedAt: "2026-05-01T14:01:00.000Z", evidence: "Approved production-shadow replay; no customer data persisted." }],
  },
  {
    id: "tr_fraud_014",
    agentName: "Fraud Ops Triage Agent",
    workflow: "alert-routing-recommendation",
    occurredAt: "2026-05-01T15:08:02.000Z",
    environment: "sandbox",
    metadataOnly: true,
    rawPromptStored: false,
    customerDataStored: false,
    redactionClass: "redacted_reference",
    retentionDays: 270,
    modelProvider: "OpenRouter",
    modelName: "openai/gpt-4o-mini",
    actionCategory: "routing-recommendation",
    policies: [
      { id: "pol_no_payload", name: "No customer payload retention", status: "pass", evidence: "Transaction references replaced with salted synthetic IDs." },
      { id: "pol_human_review", name: "Human review before escalation", status: "warn", evidence: "Reviewer SLA is 3h; current elapsed time 2h 31m." },
      { id: "pol_prompt", name: "No raw prompt storage", status: "pass", evidence: "Prompt body dropped after policy evaluation." },
    ],
    approvals: [{ reviewerRole: "Fraud operations reviewer", status: "pending", evidence: "Awaiting queue review; no escalation sent." }],
  },
  {
    id: "tr_credit_022",
    agentName: "Credit Memo Draft Assistant",
    workflow: "policy-citation-check",
    occurredAt: "2026-05-01T16:22:44.000Z",
    environment: "sandbox",
    metadataOnly: true,
    rawPromptStored: false,
    customerDataStored: false,
    redactionClass: "metadata_only",
    retentionDays: 90,
    modelProvider: "OpenRouter",
    modelName: "google/gemini-flash-1.5",
    actionCategory: "policy-citation",
    policies: [
      { id: "pol_source", name: "Approved policy-source citation", status: "pass", evidence: "Citations reference policy document IDs only." },
      { id: "pol_decision", name: "No autonomous credit decision", status: "pass", evidence: "Output classified as drafting assistance, not a customer decision." },
      { id: "pol_prompt", name: "No raw prompt storage", status: "pass", evidence: "No prompt text or customer financial data retained." },
    ],
    approvals: [{ reviewerRole: "Credit policy owner", status: "approved", decidedAt: "2026-05-01T16:50:00.000Z", evidence: "Approved for sandbox demonstration." }],
  },
];
