import { chromium } from "playwright";

const url = process.env.QA_URL || "https://complytrace.vercel.app";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const consoleErrors = [];
page.on("console", (msg) => { if (["error", "warning"].includes(msg.type())) consoleErrors.push(`${msg.type()}: ${msg.text()}`); });
page.on("pageerror", (err) => consoleErrors.push(`pageerror: ${err.message}`));
await page.goto(url, { waitUntil: "networkidle" });
const title = await page.title();
const h1 = await page.locator("h1").textContent();
await page.getByRole("link", { name: /View live demo/i }).click();
await page.getByRole("button", { name: /Run critique/i }).click();
await page.locator("pre").waitFor({ timeout: 45000 });
const critique = (await page.locator("pre").first().textContent())?.slice(0, 260);
await page.getByPlaceholder("work email").fill("qa+synthetic@complytrace.example");
await page.getByPlaceholder("company").fill("Synthetic QA Co");
await page.getByPlaceholder("role").fill("Compliance reviewer");
await page.getByPlaceholder("agent workflow to audit").fill("Synthetic refund review agent");
await page.getByRole("button", { name: /Join design partner list/i }).click();
await page.getByTestId("waitlist-status").waitFor({ timeout: 30000 });
const formStatus = (await page.getByTestId("waitlist-status").textContent())?.slice(0, 260);
const apiChecks = await page.evaluate(async () => {
  const critiqueRes = await fetch('/api/ai/audit-critique', { method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify({ focus: 'QA check' }) });
  const waitlistRes = await fetch('/api/waitlist', { method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify({ email: 'qa-api+synthetic@complytrace.example' }) });
  return { critiqueStatus: critiqueRes.status, waitlistStatus: waitlistRes.status, critiqueOk: (await critiqueRes.json()).ok, waitlistOk: (await waitlistRes.json()).ok };
});
await page.setViewportSize({ width: 390, height: 900 });
await page.goto(url, { waitUntil: "networkidle" });
const mobileH1Visible = await page.locator("h1").isVisible();
console.log(JSON.stringify({ title, h1, critique, formStatus, apiChecks, mobileH1Visible, consoleErrors }, null, 2));
await browser.close();
